import React,{useState} from 'react';
export const findings=[
['Problemi visivi','Osservati nella preview','A 390 px il titolo della chat si tronca quando compaiono voce, nuova chat e menu. I metadati hanno poco contrasto. Il riepilogo abbrevia gli importi (es. K/M) invece di mostrarli esatti e non ha scorrimento: su una finestra bassa le azioni finiscono fuori vista. La preview aggiunge scorrimento solo al contenitore browser.','MainHeader.tsx · PaymentConfirmationModal.tsx','Alleggerire header e badge; rendere la conferma scorrevole con importo esatto e azioni fisse. Distinguere dettatura e conversazione vocale.'],
['Privacy del messaggio iniziale','Testo troppo assoluto','La chat dice “nothing leaves your phone”, ma strumenti wallet e ricerca negozi fanno richieste esterne. Esecuzione locale del modello non significa assenza di comunicazioni di rete.','components/chat/ChatEmptyState.tsx · services/merchantTools.ts','Dire “Il modello gira sul dispositivo” e spiegare quali azioni usano la rete.'],
['Chat e azioni','Collegate nel codice','Chat e voce usano createMindAgent → Funnel. Saldo e ricette precedono il modello; gli strumenti di spesa passano dalla conferma. La preview esegue scenari fissi, non il wallet.','screens/AIAssistantScreen.tsx · services/mindAgent.ts','Tenere chat, azioni rapide, risultato leggibile e conferma esplicita.'],
['Personalità','Collegata, con limiti','La persona entra nel prompt dei turni agentici. Non modifica i risultati deterministici di saldo e ricette. La temperatura viene passata al provider.','services/mindAgent.ts:176 · @kaleidorg/mind/src/funnel.ts:322','Spostare in Avanzate. Esporre soprattutto lingua e risposte brevi; evitare di promettere una diversa affidabilità con “Cautious”.'],
['Memoria a lungo termine','Collegata, UX incompleta','remember/recall usano uno store condiviso tra chat e voce e AsyncStorage. Spegnere nasconde i tool, non cancella i dati; gli errori di persistenza vengono ignorati. Non è presente una vista per ispezionare le singole memorie.','services/aiMemory.ts · services/mindAgent.ts:117','Disattivata per default finché non esistono “Cosa ricordi”, modifica e cancellazione verificabile. Non salvarvi segreti.'],
['RAG / documentazione','Incompleto nel runtime','La ricerca usa il corpus Bitcoin integrato e EmbeddingGemma-300M. qvac.config.json include LLM, Whisper e TTS, non embeddings. ingest nasconde il fallimento; la promise fallita di caricamento embeddings resta memorizzata. Non c’è upload di documenti personali.','services/aiKnowledge.ts:35 · services/QVACService.ts:1039 · qvac.config.json','Nascondere RAG dalla UI ordinaria finché plugin, download, stato indice, errori e citazioni non sono verificati. Chiamarlo “Documentazione Bitcoin”.'],
['Cronologia / history kept','Collegata, non è un archivio','Short/Medium/Long significa ultimi 4/8/12 messaggi, non conversazioni. La chat usa useState: non c’è archivio persistente qui. Il limite è per messaggi, mentre il runtime locale usa 4096 token.','settingsSlice.ts · @kaleidorg/mind/src/funnel.ts:376 · AIAssistantScreen.tsx','Gestione automatica per budget di token; separare conversazioni salvate e contesto inviato al modello.'],
['MCP (i connettori)','Non collegati all’agente mobile','Nome e URL vengono salvati da MindSettings, ma MindAgentSettings e buildMindToolSources non leggono mcpServers. La UI non testa connessione, autenticazione o tool disponibili.','screens/MindSettingsScreen.tsx · services/mindAgent.ts','Togliere “Add MCP server” dalla UI utente finché non esiste il collegamento completo. Le skill integrate sono un meccanismo distinto.'],
['Skill e permessi','Attenzione alla semantica','Le skill selezionano istruzioni e strumenti. Disabilitare una skill non è un blocco di permesso: fast-path e ricette girano prima del filtro skill e i tool restano montati.','@kaleidorg/mind/src/funnel.ts:247–322','Chiamarle “Scorciatoie” o introdurre veri permessi ai tool, verificati anche fuori dal modello.'],
['Modello 4B','Visibile ma sostituito','Il catalogo mostra Qwen3.5 4B (tier pro). initializeLLM sostituisce ogni tier diverso da phone quando l’esecuzione è locale, anche con molta RAM.','services/qvacModels.ts · services/QVACService.ts:686','Mostrare modello selezionato ed effettivo. Disabilitare le opzioni non supportate e spiegare il motivo.'],
['Whisper Turbo','Selezione ed esecuzione divergono','Whisper Large v3 Turbo compare nel picker, ma sui telefoni viene caricato Whisper Base al suo posto; la configurazione conserva l’ID scelto.','services/QVACService.ts:840','Non offrire Turbo come attivo. Mostrare il motore realmente caricato e un messaggio sul fallback.'],
['Voce italiana','Problema concreto','La trascrizione multilingue usa la lingua del dispositivo. La sintesi carica TTS_EN_SUPERTONIC_Q4_0 con language en; il testo viene ridotto ad ASCII. Anche il fallback di sistema usa en-US se non riceve la lingua.','services/QVACService.ts:997 · services/qvacTts.ts:59 · services/speech.ts:86','Prima correzione: propagare la lingua, preservare accenti e usare una voce italiana installata. Valutare poi Supertonic-3.'],
['Hands-free','Implementato, da misurare','Whisper + Silero VAD → agente → TTS. Il microfono è escluso durante il playback: non è una conversazione full-duplex con interruzione vocale naturale. LLM, STT e TTS competono per memoria e il servizio scarica motori per ridurre il picco.','services/handsFreeVoice.ts · services/QVACService.ts','Mostrare ascolto, trascrizione, elaborazione e risposta. Aggiungere pausa/interruzione, misurare fine-voce → prima risposta.'],
];
const refs={qvac:'https://docs.qvac.tether.io/sdk/reference/api/',fit:'https://docs.qvac.tether.io/sdk/reference/api/#assessmodelfit',qwen:'https://huggingface.co/Qwen/Qwen3.5-2B',gemma:'https://ai.google.dev/gemma/docs/core/model_card_4',parakeet:'https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3',asr:'https://huggingface.co/Qwen/Qwen3-ASR-0.6B',supertonic:'https://github.com/supertone-oss-archive/supertonic',release:'https://qvac.tether.io/changelog/sdk-v0-20-0'};
export function ReviewPanel(){const [tab,setTab]=useState('audit');return <section className="review"><div className="eyebrow">AUDIT INIZIALE · 9 OTTOBRE 2026</div><h2>Collegamenti e limiti</h2><div className="review-tabs">{[['audit','Funzioni'],['models','Modelli'],['plan','Intervento']].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
{tab==='audit'&&<><p>Verifica: 16 test esistenti e 5 prove aggiunte sul core sono passati con dipendenze native simulate. “Collegato” non significa testato su un telefono. L’audit precede il redesign: titolo, messaggio privacy e accesso MCP sono stati rivisti. I limiti del runtime restano da risolvere.</p>{findings.map(([title,status,body,file,proposal],i)=><details key={title} open={i===2}><summary>{title}<small>{status}</small></summary><p>{body}</p><code>{file}</code><p className="recommendation">Proposta: {proposal}</p></details>)}</>}
{tab==='models'&&<><h3>Catalogo dell’app</h3><p>È una lista curata nel codice, non un catalogo aggiornato automaticamente: 3 modelli Qwen3.5 Q4_K_M. Descrittori dal registro incluso in QVAC; file GGUF via URL Hugging Face. La preview ora legge gli stessi descrittori, non pesi stimati.</p><table><thead><tr><th>Modello</th><th>Oggi nel telefono</th></tr></thead><tbody><tr><td>Qwen3.5 0.8B</td><td>Fallback / RAM &lt; 6 GiB</td></tr><tr><td>Qwen3.5 2B</td><td>Raccomandato da 6 GiB</td></tr><tr><td>Qwen3.5 4B</td><td>Elencato, ma sostituito</td></tr></tbody></table><p>È una soglia del codice, non una certificazione di compatibilità. La RAM totale non basta: contano memoria disponibile per l’app, GPU, contesto, audio contemporaneo e temperatura.</p>
<h3>Automatico per ogni utente</h3><ol><li>Rilevare piattaforma, runtime disponibile, RAM utilizzabile, spazio libero e backend CPU/GPU.</li><li>Stimare il picco di LLM + contesto + STT + TTS; gestire anche compatibilità sconosciuta.</li><li>Scegliere il profilo migliore fra quelli qualificati, non semplicemente il modello più grande.</li><li>Mostrare download totale e modello effettivo; scaricare i componenti vocali solo quando servono.</li><li>Ridurre contesto o modello se memoria, temperatura o latenza lo richiedono, spiegando il cambio.</li></ol><p>Per dispositivi non verificati: profilo leggero o funzione non disponibile; nessuna promessa basata solo sui GB di RAM. La scelta manuale rimane nelle opzioni avanzate.</p><h3>Scelta consigliata</h3><p><strong>Subito:</strong> mantenere 0.8B e 2B, profilo Automatico e contesto prudente. Non aumentare i 4096 token senza prove su device. Per un wallet misurare chiamate ai tool corrette, importi e destinatari: non solo la fluidità del testo. <a href={refs.qwen} target="_blank" rel="noreferrer">Model card Qwen</a></p>
<p><strong>Da confrontare:</strong> Gemma 4 E2B, poi E4B su telefoni adatti. Sono progettati per edge e supportano tool calling; i parametri “effettivi” non equivalgono al peso totale. Non sono integrati o certificati in questa app. <a href={refs.gemma} target="_blank" rel="noreferrer">Google: Gemma 4</a></p>
<h3>STT: capire la voce</h3><p><strong>Ora:</strong> Whisper Base multilingue come riferimento, Tiny per risparmio. Le varianti English non vanno proposte per l’italiano. Turbo è nascosto dietro il fallback del servizio.</p><p><strong>Candidato prioritario:</strong> Parakeet TDT 0.6B v3, 25 lingue incluso italiano. QVAC documenta il backend Parakeet, ma l’app non lo include: servono plugin, formato e confronto di latenza/accuratezza reali. <a href={refs.parakeet} target="_blank" rel="noreferrer">NVIDIA</a></p><p><strong>Ricerca successiva:</strong> Qwen3-ASR 0.6B. Interessante per ASR multilingue; non è una sostituzione diretta di Whisper nel servizio attuale. Verificare backend e costo di memoria prima di esporlo. <a href={refs.asr} target="_blank" rel="noreferrer">Qwen ASR</a></p>
<h3>TTS: parlare</h3><p><strong>Ora:</strong> voce italiana di sistema installata sul dispositivo, passando esplicitamente la lingua. <strong>Da provare:</strong> Supertonic-3 per sintesi multilingue, incluso italiano; il caricatore attuale usa invece un modello inglese. Il repository upstream consultato è archiviato: verificare distribuzione mantenuta e supporto QVAC prima dell’integrazione. <a href={refs.supertonic} target="_blank" rel="noreferrer">Upstream Supertonic</a></p>
<h3>SDK e aggiornamenti</h3><p>Installato: <strong>QVAC 0.13.5</strong>. La documentazione ufficiale consultata indica <strong>0.21.x</strong> e API di registro e valutazione compatibilità. Non ho aggiornato SDK o bindings. <a href={refs.qvac} target="_blank" rel="noreferrer">API correnti</a></p><p><code>assessModelFit</code> stima la compatibilità senza scaricare i pesi; è un parere, non garantisce velocità o assenza di crash. Gestire esplicitamente l’esito “unknown”. <a href={refs.fit} target="_blank" rel="noreferrer">Valutazione hardware</a></p><p>Proposta: manifest curato e versionato con hash, dimensione, lingua, quantizzazione, runtime minimo, dispositivi testati e rollback. Aggiornamento metadati separato dai download; i nuovi backend richiedono comunque una nuova build nativa.</p></>}
{tab==='plan'&&<><h3>1 · Rendere onesta la UI</h3><p>Rimuovere MCP non connessi; non proporre 4B/Turbo come disponibili; mostrare modello effettivo; correggere lingua TTS e messaggi desktop; distinguere cache di contesto e cronologia.</p><h3>2 · Ridurre le impostazioni</h3><p>Quattro scelte: modello automatico, lingua, voce e capacità. Personalità in Avanzate. Memoria opzionale con lista ispezionabile. Documentazione senza interruttore RAG fino a integrazione completa.</p><h3>3 · Qualificare i nuovi motori</h3><p>Test su almeno un telefono con poca RAM e uno di fascia alta per piattaforma. Confronto Qwen 0.8B/2B ↔ Gemma E2B; Whisper Base ↔ Parakeet; voce di sistema ↔ Supertonic-3.</p><h3>Misurare ciò che conta</h3><ul><li>Successo tool, importi/destinatari e conferma pagamento.</li><li>Italiano: nomi, sats, indirizzi, rumore, silenzio.</li><li>Tempo al primo token/audio e fine-frase → risposta, p50/p95.</li><li>RAM di picco con LLM+STT+TTS, temperatura, batteria.</li><li>Rete assente, download interrotto, spazio esaurito, background.</li><li>RAG con fonti, memoria off/cancellata, permessi anche nei fast-path.</li></ul><p>La simulazione visiva verifica navigazione e stati. Questi risultati richiedono test su hardware; non vengono dedotti da un benchmark web.</p></>}
</section>}
