import React from 'react';
import {render,fireEvent,act} from '@testing-library/react-native';
import MerchantOfferScreen from './MerchantOfferScreen';
import {createMerchantOffer,listMerchantReceipts} from '../services/kaleidoPay/merchantOffer';
import {loadMerchantOffer,saveMerchantOffer} from '../services/kaleidoPay/merchantOfferStore';
import {loadConnectedReceiverDestination} from '../services/kaleidoPay/merchantOfferWallet';
import {loadReceiverPreferences,saveReceiverPreferences,defaultReceiverPreferences} from '../services/kaleidoPay/merchantOfferPreferences';
jest.mock('../services/kaleidoPay/merchantOfferPreferences',()=>({...jest.requireActual('../services/kaleidoPay/merchantOfferPreferences'),loadReceiverPreferences:jest.fn(),saveReceiverPreferences:jest.fn()}));
const mockConnection={id:'ab'.repeat(32),walletPubkey:'ab'.repeat(32),network:'regtest',alias:'Merchant'};
jest.mock('../store/hooks',()=>({useAppSelector:(f:any)=>f({nostr:{nwcConnections:[mockConnection],selectedNwcConnectionId:mockConnection.id}})}));
jest.mock('../theme/ThemeProvider',()=>({useAppTheme:()=>require('../theme').theme}));
jest.mock('../components/ScreenHeader',()=>({ScreenHeader:'ScreenHeader'}));
jest.mock('../components/NetworkIcon',()=>({NetworkIcon:'NetworkIcon'}));
jest.mock('../components/receive/ReceiveQr',()=>({ReceiveQr:({value}:any)=>{const {Text}=require('react-native');return <Text>{value}</Text>}}));
jest.mock('../components/Button',()=>({Button:({title,onPress,disabled}:any)=>{const {Text,TouchableOpacity}=require('react-native');return <TouchableOpacity onPress={onPress} disabled={disabled}><Text>{title}</Text></TouchableOpacity>}}));
jest.mock('../services/nwc/connectionStore',()=>({loadNwcCredential:jest.fn().mockResolvedValue('private-credential')}));
jest.mock('../services/nwc/NWCExternalClient',()=>({parseNwcUri:()=>({walletPubkey:'ab'.repeat(32)}),NWCClient:class {close(){} request(){}}}));
jest.mock('../services/kaleidoPay/merchantOffer',()=>({createMerchantOffer:jest.fn(),listMerchantReceipts:jest.fn(),checkMerchantCapabilities:jest.fn().mockResolvedValue({addressPreferences:true})}));
jest.mock('../services/kaleidoPay/merchantOfferStore',()=>({loadMerchantOffer:jest.fn(),saveMerchantOffer:jest.fn(),merchantPaymentCode:(value:any)=>value.offer}));
jest.mock('../services/kaleidoPay/merchantOfferWallet',()=>({loadConnectedReceiverDestination:jest.fn()}));
jest.mock('../services/protocols',()=>({protocolManager:{getAdapterIfAvailable:(p:string)=>p==='BARK'?{getConnectionInfo:async()=>({connected:true,network:'regtest'})}:null}}));
const saved={offer:'lno1saved',offer_id:'cd'.repeat(32),network:'regtest',description:'Coffee',amount:100000};
const bark={type:'bark' as const,address:'bark-public',serverKey:'ab'.repeat(32)};
const lightning={type:'lightning' as const,source:'bolt12_offer' as const};
beforeEach(()=>{jest.clearAllMocks();(loadReceiverPreferences as jest.Mock).mockResolvedValue(defaultReceiverPreferences(mockConnection.network));(saveReceiverPreferences as jest.Mock).mockResolvedValue(undefined);(loadMerchantOffer as jest.Mock).mockResolvedValue(null);(saveMerchantOffer as jest.Mock).mockResolvedValue(undefined);(loadConnectedReceiverDestination as jest.Mock).mockResolvedValue(bark)});
const open=async()=>{const view=render(<MerchantOfferScreen navigation={{goBack:jest.fn(),navigate:jest.fn(),addListener:()=>()=>{}}}/>);await act(async()=>{});return view;};
test('reopens the saved QR and reads receipts without creating another offer',async()=>{
 (loadMerchantOffer as jest.Mock).mockResolvedValue(saved);
 (listMerchantReceipts as jest.Mock).mockResolvedValue([{payment_hash:'ef'.repeat(32),amount:100000,state:'settled'}]);
 const view=await open();
 expect(view.getAllByText('lno1saved').length).toBeGreaterThan(0);expect(createMerchantOffer).not.toHaveBeenCalled();
 await act(async()=>{fireEvent.press(view.getByText('Refresh payments'))});
 expect(view.getByText('1 received')).toBeTruthy();
});
test('persists an offer before showing the reusable QR',async()=>{
 (createMerchantOffer as jest.Mock).mockResolvedValue(saved);
 const view=await open();
 fireEvent.press(view.getByText('Fixed amount'));
 fireEvent.changeText(view.getByLabelText('Reusable QR amount in sats'),'100');
 await act(async()=>{fireEvent.press(view.getByText('Create payment QR'))});
 expect(saveMerchantOffer).toHaveBeenCalledWith(mockConnection.id,expect.objectContaining({offer:'lno1saved',network:'regtest'}));
 expect(view.getAllByText('lno1saved').length).toBeGreaterThan(0);
});
test('storage failure never displays an unpersisted QR',async()=>{
 (createMerchantOffer as jest.Mock).mockResolvedValue(saved);(saveMerchantOffer as jest.Mock).mockRejectedValue(new Error('Storage unavailable'));
 const view=await open();
 await act(async()=>{fireEvent.press(view.getByText('Create payment QR'))});
 expect(view.queryByText('lno1saved')).toBeNull();expect(view.getByText('Storage unavailable')).toBeTruthy();
});
test('adds the connected account address without manual address or server key fields',async()=>{
 (loadMerchantOffer as jest.Mock).mockResolvedValue(saved);
 const view=await open();
 fireEvent.press(view.getByText('Edit payment QR'));
 await act(async()=>{fireEvent.press(view.getByLabelText('Add connected Bark account'))});
 expect(loadConnectedReceiverDestination).toHaveBeenCalledWith('bark','regtest');
 expect(view.queryByLabelText('Bark receiving address')).toBeNull();
 expect(view.queryByLabelText('Bark server public key')).toBeNull();
 expect(view.queryByText('Advanced')).toBeNull();
 expect(view.queryByLabelText('Add Bitcoin on-chain')).toBeNull();
 fireEvent.press(view.getByLabelText('Move Lightning up'));
 await act(async()=>{fireEvent.press(view.getByText('Save as my defaults'))});
 expect(saveReceiverPreferences).toHaveBeenCalledWith(mockConnection.id,expect.objectContaining({destinations:[lightning,bark]}));
 expect(view.getAllByText('lno1saved').length).toBeGreaterThan(0);expect(createMerchantOffer).not.toHaveBeenCalled();
});
test('drops a previously saved on-chain address from the receiving order',async()=>{
 (loadReceiverPreferences as jest.Mock).mockResolvedValue({version:1,network:'regtest',destinations:[{type:'bitcoin',address:'bcrt1qtyped'},bark,lightning]});
 const view=await open();
 expect(view.queryByText(/bcrt1qtyped/)).toBeNull();
 await act(async()=>{fireEvent.press(view.getByText('Save as my defaults'))});
 expect(saveReceiverPreferences).toHaveBeenCalledWith(mockConnection.id,expect.objectContaining({destinations:[bark,lightning]}));
});
test('failed replacement preserves old QR and retries storage without issuing again',async()=>{
 (loadMerchantOffer as jest.Mock).mockResolvedValue(saved);
 (createMerchantOffer as jest.Mock).mockResolvedValue({...saved,offer:'lno1updated'});
 (saveMerchantOffer as jest.Mock).mockRejectedValueOnce(new Error('Storage unavailable')).mockResolvedValueOnce(undefined);
 const view=await open();
 fireEvent.press(view.getByText('Edit payment QR'));
 await act(async()=>{fireEvent.press(view.getByText('Create updated QR'))});
 expect(view.getAllByText('lno1saved').length).toBeGreaterThan(0);expect(view.queryByText('lno1updated')).toBeNull();
 await act(async()=>{fireEvent.press(view.getByText('Create updated QR'))});
 expect(view.getAllByText('lno1updated').length).toBeGreaterThan(0);expect(createMerchantOffer).toHaveBeenCalledTimes(1);
});
