"""Reuse the reviewed continuous mesh in the native, audio-free renderer."""
from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
src = (root/'preview/prismo-3d/animate-original.js').read_text()
core = src[src.index('// One continuous'):src.index('let context,analyser,samples;')]
core = core.replace('n=160', 'n=96').replace('gl.viewport(0,0,1280,1280)', 'gl.viewport(0,0,resolution,resolution)')
tail = '''
let phase='idle',level=0,paused=false,reduced=false,time=0,last=performance.now(),lastLevel=0,mouth=1,wave=0,frame;
const smooth=(a,b,dt,k)=>a+(b-a)*(1-Math.exp(-k*dt));
window.prismoUpdate=state=>{
 if(state.phase!==undefined){phase=state.phase;if(phase!=='speaking')level=0;}
 if(state.level!==undefined){level=Math.max(0,Math.min(1,state.level));lastLevel=performance.now();}
 if(state.paused!==undefined)paused=state.paused;
 if(state.reduced!==undefined)reduced=state.reduced;
 if(!paused&&!frame){last=performance.now();frame=requestAnimationFrame(render);}
};
function render(now){
 frame=0;if(paused)return;
 if(now-last<1000/30){frame=requestAnimationFrame(render);return;}
 const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;
 const energy=now-lastLevel<350?level:0;
 mouth=smooth(mouth,phase==='speaking'?energy:1,dt,20);
 const greeting=time<3.5&&!reduced?ease(time/.8)*ease((3.5-time)/.9)*Math.sin(time*5.8)*.10:0;
 wave=smooth(wave,greeting,dt,13);
 const bt=time%3.7-3.2;
 const blink=reduced||bt<0||bt>.34?0:bt<.12?Math.sin(bt/.12*Math.PI/2):bt<.17?1:Math.cos((bt-.17)/.17*Math.PI/2);
 gl.clear(gl.COLOR_BUFFER_BIT);
 gl.uniform1f(uniforms.wave,wave);gl.uniform1f(uniforms.openness,mouth);
 gl.uniform1f(uniforms.width,1);gl.uniform1f(uniforms.blink,blink);
 gl.uniform1f(uniforms.breathe,reduced?0:Math.sin(time*1.7));
 gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);
 if(!reduced||phase==='speaking')frame=requestAnimationFrame(render);
}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);window.ReactNativeWebView?.postMessage('failed');});
window.ReactNativeWebView?.postMessage('ready');frame=requestAnimationFrame(render);
'''
js="const canvas=document.querySelector('canvas');canvas.width=resolution;canvas.height=resolution;const load=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});const [original,closedEyes]=await Promise.all(images.map(load));\n"+core+tail
out='// Generated by scripts/build-prismo-renderer.py; no audio or wallet data in this renderer.\nconst renderer = '+json.dumps(js)+';\n'
out+='''export function prismoAnimationHtml(images: string[], pixelSize = 416): string {
 const resolution = Math.max(96, Math.min(640, Math.round(pixelSize) || 416));
 return `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><style>html,body{margin:0;background:transparent;overflow:hidden}canvas{width:100vw;height:100vw;display:block}</style><canvas></canvas><script type="module">const images=${JSON.stringify(images)},resolution=${resolution};try{${renderer}}catch(e){window.ReactNativeWebView?.postMessage('failed');}</script>`;
}
'''
(root/'components/mind/prismoAnimationHtml.ts').write_text(out)
