"""Bundle the reviewed 2D demo for offline, development-only simulator review."""
from pathlib import Path
import base64,json
root=Path(__file__).resolve().parents[1]
src=root/'preview/prismo-3d'
js=(src/'animate-original.js').read_text()
for name in ['original.png','eyes-closed.png']:
 js=js.replace("'"+name+"'",json.dumps('data:image/png;base64,'+base64.b64encode((src/name).read_bytes()).decode()))
js=js.replace("await fetch('./audio/alignment.json').then(r=>r.json())",(src/'audio/alignment.json').read_text())
audio='data:audio/mpeg;base64,'+base64.b64encode((src/'audio/prismo-it.mp3').read_bytes()).decode()
html='''<!doctype html><html lang="it"><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><style>
*{box-sizing:border-box}body{margin:0;background:#10111b;color:#f3f5ff;font:16px -apple-system,sans-serif;text-align:center}main{padding:8px 20px 18px;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:space-between}canvas{width:min(100%,290px);height:auto;aspect-ratio:1}h2{font-size:23px;font-weight:600;margin:8px 0 16px}p{font-size:12px;color:#aab2c6;line-height:1.5;margin:8px 0}button{font:inherit;min-height:48px;border:0;border-radius:24px;background:#242637;color:#eff5ff;padding:12px 16px}#demo{background:#00dfa9;color:#002e24;width:100%;font-weight:600}.controls{display:flex;gap:10px;justify-content:center;margin:12px 0}.controls button{flex:1;padding:12px 8px;font-size:14px}button[aria-pressed=true]{outline:1px solid #00dfa9}section{width:100%;max-width:360px}#pause{width:100%;margin-top:0}#ready{font-size:11px}@media(max-height:540px){canvas{width:200px}h2{font-size:19px;margin:4px}main{padding:8px 16px}button{min-height:44px;padding:8px}}
</style></head><body><main><section><p>DEMO VOCALE · MICROFONO NON ATTIVO</p><canvas id="prismo" role="img" aria-label="Prismo originale animato"></canvas><h2 id="status" aria-live="polite">Ciao, sono Prismo.</h2></section><section><button id="demo">Ascolta e guarda Prismo</button><div class="controls"><button data-mode="wave" aria-pressed="false">Saluta</button><button data-mode="blink" aria-pressed="false">Occhi</button><button data-mode="talk" aria-pressed="false">Parla</button></div><button id="pause">Pausa</button><p id="ready">Caricamento…</p><p>Voce italiana di esempio. Nessun pagamento.</p></section></main><audio id="voice" preload="auto" src="'''+audio+'''"></audio><script type="module">'''+js+'''</script></body></html>'''
(root/'components/mind/prismoTalkPreviewHtml.ts').write_text('// Generated by scripts/build-prismo-talk-preview.py. Development preview only.\nexport const prismoTalkPreviewHtml = '+json.dumps(html)+';\n')
print('Offline Talk demo bundled')
